### ISSUE TITLE
Орфографическая ошибка

### ISSUE THREAD

**Issue by husker-dev** [Fooxboy/Music-X-Player#1]
Я считаю, что в данном приложении !!недопустимы!! орфографические ошибки
![image](https://user-images.githubusercontent.com/31825139/96347657-d7265e00-10ab-11eb-916f-087b18711f36.png)

**Comment by Fooxboy** [comment]
![изображение](https://user-images.githubusercontent.com/31418624/96347788-9a0e9b80-10ac-11eb-9223-04a64262f23d.png)
