### ISSUE TITLE
Интересный мультиплатформенный проект. Спасибо!

### ISSUE THREAD

**Issue by mediaexplorer74** [Fooxboy/Music-X-Player#4]
Fooxboy, Привет!
 Интересный мультиплатформенный проект. Спасибо! Будет время, качну покурить, как там что =)
Вопросик навскид: а проект Fooxboy.MusicX.Server для чего служит, не вдупляю? Имитация сервиса ВК-музыки или неа?
С уважением,
Андрей aka MediaExplorer

**Comment by Fooxboy** [comment]
Привет! Сервер никак не используется, задумывалось его делать для совместного прослушивания между пользователями. Но руки так и не дошли. По поводу плеера- это старая версия, новая пока что не имеет отрытого кода. Она написана с нуля на wpf. Если интересно, вот группа в телеге  https://t.me/MusicXPlayer
Если интересно, могу открыть доступ к сурсам норвго,  если есть желания развивать, то ещё лучше :) 
Можешь написать в комментах, я в ЛС отпишу
